-- 随机生成 10 条宠物数据 (Seed Data)
-- 包含 狗狗、猫咪 和 其他宠物
-- 图片使用 Unsplash 的高质量图片，确保国内可访问

INSERT INTO public.pets (
    id,
    name, 
    type, 
    breed, 
    age, 
    gender, 
    weight, 
    description, 
    image_url, 
    status, 
    distance, 
    health_tags, 
    requirements,
    created_at
) VALUES 
(
    gen_random_uuid(),
    '巴弟', 
    'dog', 
    '金毛猎犬', 
    '2岁', 
    'male', 
    '28kg', 
    '巴弟是一只非常友好的金毛，喜欢玩球和游泳。性格温顺，适合有孩子的家庭。', 
    'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=80', 
    'available', 
    '1.2 km', 
    ARRAY['{"id":"vaccinated","label":"已疫苗","icon":"vaccines","color":"green"}', '{"id":"neutered","label":"已绝育","icon":"healing","color":"purple"}']::jsonb[],
    ARRAY['需要每天遛弯', '最好有院子', '接受定期回访'],
    NOW()
),
(
    gen_random_uuid(),
    '米斯蒂', 
    'cat', 
    '虎斑猫', 
    '8个月', 
    'female', 
    '3.5kg', 
    '米斯蒂有些害羞，但熟悉后非常粘人。喜欢在窗台上晒太阳。', 
    'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80', 
    'available', 
    '0.8 km',
    ARRAY['{"id":"vaccinated","label":"已疫苗","icon":"vaccines","color":"green"}']::jsonb[],
    ARRAY['仅限室内饲养', '家里有纱窗'],
    NOW()
),
(
    gen_random_uuid(),
    '奥利奥', 
    'dog', 
    '边境牧羊犬', 
    '1岁', 
    'male', 
    '20kg', 
    '精力充沛的边牧，非常聪明，需要大量运动。适合喜欢户外运动的主人。', 
    'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80', 
    'available', 
    '5.4 km',
    ARRAY['{"id":"vaccinated","label":"已疫苗","icon":"vaccines","color":"green"}', '{"id":"dewormed","label":"已驱虫","icon":"medication","color":"blue"}']::jsonb[],
    ARRAY['有养狗经验', '每天运动2小时以上'],
    NOW()
),
(
    gen_random_uuid(),
    '露娜', 
    'cat', 
    '暹罗猫', 
    '2岁', 
    'female', 
    '4kg', 
    '典型的暹罗性格，喜欢聊天，粘人。毛色很漂亮。', 
    'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=800&q=80', 
    'available', 
    '2.5 km',
    ARRAY['{"id":"neutered","label":"已绝育","icon":"healing","color":"purple"}']::jsonb[],
    ARRAY['接受多宠家庭', '科学喂养'],
    NOW()
),
(
    gen_random_uuid(),
    '豆豆', 
    'dog', 
    '柯基', 
    '3岁', 
    'male', 
    '12kg', 
    '小短腿，大屁股。性格憨厚，对人友善。虽然腿短但跑得很快！', 
    'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=800&q=80', 
    'available', 
    '3.0 km',
    ARRAY['{"id":"vaccinated","label":"已疫苗","icon":"vaccines","color":"green"}']::jsonb[],
    ARRAY['注意腰椎保护', '控制体重'],
    NOW()
),
(
    gen_random_uuid(),
    '雪球', 
    'cat', 
    '布偶猫', 
    '1.5岁', 
    'female', 
    '5.5kg', 
    '像洋娃娃一样乖巧，毛发蓬松柔软。性格极其温顺，任人抱。', 
    'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=800&q=80', 
    'available', 
    '4.2 km',
    ARRAY['{"id":"vaccinated","label":"已疫苗","icon":"vaccines","color":"green"}', '{"id":"neutered","label":"已绝育","icon":"healing","color":"purple"}']::jsonb[],
    ARRAY['需要经常梳毛', '家里环境安静'],
    NOW()
),
(
    gen_random_uuid(),
    '洛基', 
    'dog', 
    '哈士奇', 
    '2岁', 
    'male', 
    '25kg', 
    '虽然是哈士奇，但意外地比较听话。表情包产出户，能给你带来很多欢乐。', 
    'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=800&q=80', 
    'available', 
    '6.8 km',
    ARRAY['{"id":"vaccinated","label":"已疫苗","icon":"vaccines","color":"green"}']::jsonb[],
    ARRAY['有耐心', '牢固的牵引绳'],
    NOW()
),
(
    gen_random_uuid(),
    '摩卡', 
    'cat', 
    '中华田园猫', 
    '6个月', 
    'female', 
    '2.8kg', 
    '一只可爱的三花猫，是在小区花园救助的。现在已经完全适应室内生活了。', 
    'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=800&q=80', 
    'available', 
    '1.5 km',
    ARRAY['{"id":"dewormed","label":"已驱虫","icon":"medication","color":"blue"}']::jsonb[],
    ARRAY['适龄绝育', '领养代替购买'],
    NOW()
),
(
    gen_random_uuid(),
    '查理', 
    'dog', 
    '拉布拉多', 
    '4岁', 
    'male', 
    '30kg', 
    '退役导盲犬（淘汰），性格极其稳定，不乱叫不咬人。', 
    'https://images.unsplash.com/photo-1591769225440-811ad7d6eab2?auto=format&fit=crop&w=800&q=80', 
    'available', 
    '8.0 km',
    ARRAY['{"id":"vaccinated","label":"已疫苗","icon":"vaccines","color":"green"}', '{"id":"neutered","label":"已绝育","icon":"healing","color":"purple"}']::jsonb[],
    ARRAY['陪伴时间充足', '善待功勋犬'],
    NOW()
),
(
    gen_random_uuid(),
    '小黑', 
    'cat', 
    '黑猫', 
    '1岁', 
    'male', 
    '4.2kg', 
    '黑猫警长！眼睛像铜铃。性格机灵有趣，会玩捡球游戏。', 
    'https://images.unsplash.com/photo-1557246565-8a3d955d7426?auto=format&fit=crop&w=800&q=80', 
    'available', 
    '2.2 km',
    ARRAY['{"id":"vaccinated","label":"已疫苗","icon":"vaccines","color":"green"}']::jsonb[],
    ARRAY['真心喜欢黑猫', '科学喂养'],
    NOW()
);
